# Generated by Django 6.1.1 on 2026-09-10 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hotels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="hotelimages",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hotels.hotel"
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hotels.hotel"
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="room_categories",
            field=models.ManyToManyField(to="hotels.roomcategory"),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="room_facilities",
            field=models.ManyToManyField(to="hotels.facilities"),
        ),
        migrations.AddField(
            model_name="roomimages",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hotels.roomtype"
            ),
        ),
    ]
