# Generated by Django 6.1.1 on 2026-09-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="adress",
            field=models.CharField(default="astana district", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hotel",
            name="hotel_contact_email",
            field=models.EmailField(default="lll", max_length=254),
            preserve_default=False,
        ),
    ]
