# Generated by Django 6.1.1 on 2026-09-11 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0003_hotel_adress_hotel_hotel_contact_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="adress",
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="hotel_contact_email",
        ),
        migrations.AlterField(
            model_name="hotelimages",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hotel_images",
                to="hotels.hotel",
            ),
        ),
    ]
