# Generated by Django 6.1.1 on 2026-09-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hotels",
            "0004_remove_hotel_adress_remove_hotel_hotel_contact_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="hotel_description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="hotel_description_kk",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="hotel_description_ru",
            field=models.TextField(null=True),
        ),
    ]
