# Generated by Django 6.1.1 on 2026-09-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0005_hotel_hotel_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="hotel_name_en",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="hotel_name_kk",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="hotel_name_ru",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
