# Generated by Django 6.1.1 on 2026-09-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0006_hotel_hotel_name_en_hotel_hotel_name_kk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="max_guests_amount",
            field=models.PositiveBigIntegerField(default=3),
            preserve_default=False,
        ),
    ]
