# Generated by Django 6.1.1 on 2026-09-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0007_roomtype_max_guests_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roomimages",
            old_name="hotel",
            new_name="room",
        ),
        migrations.AddField(
            model_name="roomtype",
            name="room_description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="room_description_kk",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="room_description_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="room_title_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="room_title_kk",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="room_title_ru",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
