# Generated by Django 6.1.1 on 2026-09-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0008_rename_hotel_roomimages_room_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilities",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="facilities",
            name="name_kk",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="facilities",
            name="name_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="roomcategory",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="roomcategory",
            name="name_kk",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="roomcategory",
            name="name_ru",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
