# Generated by Django 6.1.1 on 2026-09-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0009_facilities_name_en_facilities_name_kk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilities",
            name="images",
            field=models.ImageField(default="image", upload_to="facilitiesimages"),
            preserve_default=False,
        ),
    ]
