# Generated by Django 6.1.1 on 2026-09-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0010_facilities_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facilities",
            name="images",
        ),
        migrations.AddField(
            model_name="facilities",
            name="facility_svg",
            field=models.TextField(default="svg"),
            preserve_default=False,
        ),
    ]
