# Generated by Django 6.1.1 on 2026-09-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0011_remove_facilities_images_facilities_facility_svg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="hotel_name_en",
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="hotel_name_kk",
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="hotel_name_ru",
        ),
    ]
