# Generated by Django 6.1.1 on 2026-09-17 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0012_remove_hotel_hotel_name_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelimages",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hotels.hotel"
            ),
        ),
    ]
