# Generated by Django 6.1.1 on 2026-09-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0013_alter_hotelimages_hotel"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="address",
            field=models.TextField(default="address"),
            preserve_default=False,
        ),
    ]
