# Generated by Django 6.1.1 on 2026-10-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("checked_out", "Checked Out"),
                ],
                default="active",
            ),
        ),
    ]
